version: '3'

volumes:
  postgres_volume:

services:
  pg:
    image: postgres:14-alpine3.17
    env_file:
      - ".env"
    ports:
      - "5678:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  #migrator:
  #  build:
  #    context: .
  #    dockerfile: migrations.Dockerfile
  #  restart: on-failure
  #  environment:
  #    DB_HOST: pg